Rubocop fixes
bbc/frameworks-capybara pull request #7
Opened 2017-07-25 15:44 UTC by SwatiTabib

2017-07-25 15:47 UTC, SwatiTabib commented
Out of 1083, 968 offences are resolved!

2017-07-25 16:31 UTC, pratyush23 commented
👍

2017-07-25 16:49 UTC, ankitjain0105 requested changes
Just few things i have mentioned, please have a look.
Great work Swati...

2017-07-25 16:49 UTC, ankitjain0105 commented on lib/frameworks/capybara.rb
> +    # return profile
do we need to remove this ?

2017-07-25 16:49 UTC, ankitjain0105 commented on lib/frameworks/capybara.rb
> +      Capybara.app_host = 'http://www.bbc.co.uk'
does it mean that it will run only on live ?

2017-07-25 16:49 UTC, ankitjain0105 commented on lib/frameworks/capybara.rb
> +          'binary' => '/Users/tabibs01/Downloads/chrome-linux/chrome',
Need to find the solution to make it generic location for e.g. keeping it in repo, thoughts ?

2017-07-26 10:19 UTC, PriyaRam24 reviewed
Looks good.Great work

2017-07-26 10:32 UTC, SwatiTabib commented on lib/frameworks/capybara.rb
> +    # return profile
not now, I want to check if everything is ok on jenkins jobs before I remove

2017-07-26 10:32 UTC, SwatiTabib commented on lib/frameworks/capybara.rb
> +      Capybara.app_host = 'http://www.bbc.co.uk'
this method shouldn't be a part of this PR I am taking out this

2017-07-26 10:32 UTC, SwatiTabib commented on lib/frameworks/capybara.rb
> +          'binary' => '/Users/tabibs01/Downloads/chrome-linux/chrome',
see above

2017-07-26 10:33 UTC, SwatiTabib commented
@ankitjain0105 : removed chrome driver code for now.

2017-07-26 10:48 UTC, ankitjain0105 approved these changes

2017-07-26 10:48 UTC, ankitjain0105 commented
Thanks Swati :shipit:

2017-07-28 14:31 UTC, merged